## Table of Content

- [1. Introduction to Numpy](#1)
    - [1.1. What is Numpy and why it is essential for machine learning?](#1-1)
    - [1.2. Installing Numpy and setting up the development environment](#1-2)
- [2. Numpy Arrays](#2)
    - [2.1. Creating Numpy arrays using np.array()](#2-1)
    - [2.2. Understanding array shapes and dimensions](#2-2)
    - [2.3. Analogy between Numpy arrays and mathematical data structures](#2-3)
    - [2.4. Accessing and modifying array elements](#2-4)
    - [2.5. Basic array operations (element-wise operations, broadcasting)](#2-5)
    - [2.6. Array indexing and slicing](#2-6)






    
    

<a name='1'></a>
# 1. Introduction to Numpy

<a name='1-1'></a>
## 1.1. What is Numpy and why it is essential for machine learning?

`Numpy` is a powerful Python library that stands for _'Numerical Python'_. It provides support for large, multi-dimensional arrays and matrices, along with a vast collection of mathematical functions to operate on these arrays efficiently. 

`Numpy` is essential for machine learning because it enables fast and efficient numerical computations, making it possible to work with large datasets and perform complex mathematical operations with ease. Its ability to handle arrays and matrices efficiently allows for concise and optimized code implementations of various machine learning algorithms.

<a name='1-2'></a>
## 1.2. Installing Numpy and setting up the development environment

To get started with `Numpy`, we first need to install the library and set up our development environment. Follow the steps below to install `Numpy` and set up a Jupyter notebook:

### Step 1: Install Numpy

1. Open your command prompt or terminal (e.g., Press Command + Space Bar on your Mac keyboard and Type in “Terminal").
2. If you have Python installed, you can install `Numpy` by running the following command:
`pip install numpy`. This command will download and install `Numpy` from the Python Package Index (PyPI).

### Step 2: Set up Jupyter Notebook

Jupyter Notebook is an interactive coding environment that allows you to create and share documents containing code, visualizations, and explanatory text. Here's how to set it up:

1. Install Jupyter Notebook by running the following command in your command prompt or terminal: `pip install jupyter`
2. Launch Jupyter Notebook by typing the following command and pressing Enter: `jupyter notebook`. This will open Jupyter Notebook in your default web browser.
3. In the Jupyter Notebook interface, click on "New" and select "Python 3" to create a new Python notebook.

### Step 3: Importing Numpy

In your Jupyter notebook, you need to import the `Numpy` library before using its functions and features. To import Numpy, add the following line of code at the beginning of your notebook:

```python
`import numpy as np`

**Note:** By convention, `Numpy` is often imported with the alias `np`, which allows us to use the shorthand notation `np` when referring to `Numpy` functions throughout our notebook.

That's it! You have successfully installed `Numpy` and set up your Jupyter notebook environment. Now, you're ready to dive into the basics of `Numpy` and explore its powerful capabilities for machine learning.

<a name='2'></a>
# 2. Numpy Arrays

`Numpy` arrays are the foundation of the `Numpy` library and provide a powerful way to store and manipulate data. In this section, we will explore various aspects of `Numpy` arrays, starting with creating arrays using the `np.array()` function.

<a name='2-1'></a>
### 2.1. Creating Numpy arrays using np.array()

To create a `Numpy` array, you can use the `np.array()` function and provide a Python list or tuple as an argument. The `np.array()` function converts the input into a Numpy array. Here's an example:

In [10]:
# Create a Numpy array from a Python list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_array)

[1 2 3 4 5]


In the example above, we created a `Numpy` array `my_array` from a Python list `my_list` using the `np.array()` function. The resulting `Numpy` array contains the same elements as the original list.

`Numpy` arrays are homogeneous, meaning they can only contain elements of the same data type. If the elements in the input list have different data types, Numpy will attempt to convert them to a common data type. For example:

In [11]:
my_list = [1, 2.5, "hello", True]
my_array = np.array(my_list)

print(my_array)

['1' '2.5' 'hello' 'True']


In this case, the elements in the input list have different data types (integer, float, string, and a boolean). `Numpy` converts all the elements to strings, resulting in a `Numpy` array of strings.

It's important to note that `Numpy` arrays are fixed in size once created. If you try to append or remove elements from a Numpy array, a new array will be created with the updated elements. Therefore, Numpy arrays are not designed to be dynamically resizable like Python lists.

That's it for creating `Numpy` arrays using the `np.array()` function.

<a name='2-2'></a>
### 2.2. Understanding array shapes and dimensions

`Numpy` arrays can have different shapes and dimensions, which define the structure and size of the array. In this subsection, we will explore how to determine the shape and dimensions of a `Numpy` array.

#### Shape of an Array

The shape of a `Numpy` array refers to the number of elements along each dimension of the array. You can access the shape of an array using the `shape` attribute. Here's an example:

In [12]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array.shape)

(2, 3)


In this example, my_array is a **2-dimensional** array with 2 rows and 3 columns. The shape attribute returns a tuple `(2, 3)` indicating the shape of the array.

If you have a **1-dimensional** array, the shape will be a single number representing the size of the array. For example:

In [13]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array.shape)

(5,)


In this case, `my_array` is a **1-dimensional** array with 5 elements. The `shape` attribute returns a tuple `(5,)` indicating the shape of the array. 

Here's an example of a **3-dimensional** array:

In [15]:
my_array = np.array([ [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]] ])
print(my_array.shape)

(3, 3, 3)


#### Dimensions of an Array

The dimensions of a `Numpy` array refer to the number of axes or dimensions it has. You can determine the number of dimensions using the `ndim` attribute. Here's an example:

In [16]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array.ndim)

2


In this example, `my_array` is a **2-dimensional** array, so the `ndim` attribute returns `2`.

If you have a **1-dimensional** array, the `ndim` attribute will return `1`. For example:

In [17]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array.ndim)

1


Understanding the shape and dimensions of a `Numpy` array is crucial when working with multi-dimensional arrays, as it helps you correctly access and manipulate the array elements.

<a name='2-3'></a>
### 2.3. Analogy between Numpy arrays and mathematical data structures

`Numpy` arrays can be thought of as multi-dimensional counterparts to **basic mathematical data structures** such as **scalars**, **vectors**, and **matrices**. Here's an analogy to help you understand this relationship:

1. **Scalars:**
- In mathematics, a scalar is a single numerical value, representing magnitude but not direction.
- In `Numpy`, a scalar is the simplest form of an array, with zero dimensions. It represents a single value.
- Analogously, a `Numpy` scalar can be seen as the equivalent of a scalar in mathematics.

2. Vectors:
- In mathematics, a vector is a one-dimensional array of values, with both magnitude and direction.
- In `Numpy`, a one-dimensional array represents a vector.
- Analogously, a `Numpy` one-dimensional array can be seen as the equivalent of a vector in mathematics.

3. Matrices:
- In mathematics, a matrix is a two-dimensional array of values, arranged in rows and columns.
- In `Numpy`, a two-dimensional array represents a matrix.
- Analogously, a `Numpy` two-dimensional array can be seen as the equivalent of a matrix in mathematics.

4. n-dimensional arrays:
- In mathematics, higher-dimensional arrays can be thought of as extensions of vectors and matrices.
- In `Numpy`, n-dimensional arrays represent arrays with more than two dimensions.
- Analogously, a `Numpy` n-dimensional array can be seen as the extension of vectors and matrices to higher dimensions.

By leveraging the power of n-dimensional arrays, `Numpy` provides a versatile framework for handling and manipulating data in various dimensions, making it well-suited for tasks in **machine learning** and **scientific computing**.

**Note:** It's important to note that while the analogy helps in understanding the relationship between `Numpy` arrays and mathematical data structures, `Numpy` arrays also have additional capabilities and functionalities specific to array operations, broadcasting, and other numerical computations.

<a name='2-4'></a>
### 2.4. Accessing and modifying array elements

`Numpy` arrays provide convenient ways to access and modify individual elements or subsets of elements within the array.

#### Accessing Array Elements

You can access specific elements in a `Numpy` array using indexing. `Numpy` arrays are zero-indexed, which means the first element has an index of `0`. Here are a few examples:

In [21]:
my_array = np.array([1, 2, 3, 4, 5])

# Access the first element
print(my_array[0])  # Output: 1

# Access the third element
print(my_array[2])  # Output: 3

# Access the last element
print(my_array[-1])  # Output: 5

1
3
5


In this example, `my_array` is a **1-dimensional** array. We use square brackets `[]` with the desired index to access specific elements. Negative indices can be used to access elements from the end of the array.

For multi-dimensional arrays, you can use multiple indices to access elements in different dimensions. Here's an example with a **2-dimensional** array:

In [25]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])

# Access the element at row 0, column 1
print(my_array[0, 1])  # Output: 2

# Access the element at row 1, column 2
print(my_array[1, 2])  # Output: 6

2
6


In this case, `my_array` is a **2-dimensional** array. We use comma-separated indices within the square brackets to access specific elements based on their row and column positions.

#### Modifying Array Elements

`Numpy` arrays allow you to modify individual elements or subsets of elements by assigning new values. Here are a few examples:

In [29]:
my_array = np.array([1, 2, 3, 4, 5])

# Modify the second element
my_array[1] = 10
print(my_array)  # Output: [1, 10, 3, 4, 5]

# Modify a subset of elements (from the third element to the last element)
my_array[2:] = [20, 30, 40]
print(my_array)  # Output: [1, 10, 20, 30, 40]

[ 1 10  3  4  5]
[ 1 10 20 30 40]


In this example, we first modify the second element of `my_array` by assigning a new value. Then, we modify a subset of elements from index 2 to 4 (inclusive) by assigning a new list of values.

For multi-dimensional arrays, you can modify elements in a similar way using indexing. Here's an example:

In [30]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])

# Modify the element at row 1, column 0
my_array[1, 0] = 10
print(my_array)

[[ 1  2  3]
 [10  5  6]]


In this case, we modify the element at row `1` and column `0` by assigning a new value.

Understanding how to access and modify array elements is fundamental when working with Numpy arrays, as it allows you to extract and update the data within the arrays based on your specific needs.

<a name='2-5'></a>
### 2.5. Basic array operations (element-wise operations, broadcasting)

`Numpy` arrays support various basic operations that can be performed element-wise on the arrays. These operations include arithmetic operations, mathematical functions, and logical operations. In this subsection, we will explore how to perform element-wise operations and utilize broadcasting in `Numpy`.

#### Element-wise Operations

Element-wise operations allow you to perform arithmetic operations or apply mathematical functions to each element in a `Numpy` array independently. Here are a few examples:

In [33]:
my_array = np.array([1, 2, 3, 4, 5])

# Addition
result_add = my_array + 2
print(result_add)  # Output: [3, 4, 5, 6, 7]

# Subtraction
result_subtract = my_array - 2
print(result_subtract)  # Output: [-1, 0, 1, 2, 3]

# Multiplication
result_multiply = my_array * 2
print(result_multiply)  # Output: [2, 4, 6, 8, 10]

# Division
result_divide = my_array / 2
print(result_divide)  # Output: [0.5, 1.0, 1.5, 2.0, 2.5]

# Exponentiation
result_power = my_array ** 2
print(result_power)  # Output: [1, 4, 9, 16, 25]

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]


In this example, we perform various arithmetic operations (addition, subtraction, multiplication, division, and exponentiation) on `my_array`, resulting in new arrays with the element-wise operation applied.

`Numpy` also provides a wide range of mathematical functions that can be applied element-wise to arrays, such as `np.sin()`, `np.cos()`, `np.exp()`, etc. Here's an example:

In [35]:
my_array = np.array([0, np.pi/2, np.pi])

# Sine function
result_sin = np.sin(my_array)
print(result_sin)  # Output: [0.0, 1.0, 1.2246468e-16]

# Exponential function
result_exp = np.exp(my_array)
print(result_exp)  # Output: [ 1., 4.81047738, 23.14069263]

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          4.81047738 23.14069263]


In this case, we apply the `np.sin()` and `np.exp()` functions to `my_array`, resulting in new arrays with the element-wise function applied.

#### Broadcasting

Broadcasting is a powerful feature in `Numpy` that enables operations between arrays of different shapes or dimensions. `Numpy` automatically performs broadcasting when certain conditions are met. Here's an example:

In [37]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

result_broadcast = my_array * scalar
print(result_broadcast)

[[ 2  4  6]
 [ 8 10 12]]


In this example, we multiply a **2-dimensional** array my_array with a scalar value `scalar`. `Numpy` automatically broadcasts the `scalar` to match the shape of the array, and the element-wise multiplication is performed accordingly.

**Broadcasting** allows for concise and efficient code implementation, eliminating the need for explicit loops or repetitions when operating on arrays of different shapes.

Understanding and utilizing element-wise operations and broadcasting in `Numpy` are essential when performing mathematical computations and transformations.